### ISSUE TITLE
代码缺失

### ISSUE THREAD

**Issue by Fi-github** [speedcell4/nersted#1]
运行代码时发现pipe.py文件下
WordPipe文件没有build_vocab方法导致出现错误
AttributeError: 'WordPipe' object has no attribute 'build_vocab'

**Comment by speedcell4** [comment]
Hi, thanks for your interest.

Please reinstall the `torchglyph` library by `python3 -m pip install torchglyph==0.2.0` and try again, if it still doesn't work, please post the complete error information here.

**Comment by Fi-github** [comment]
> 

Thank you for your reply！
Problem solved.
But there is a new issues have emerged：
Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zyf/nersted/ner/__main__.py", line 9, in <module>
    app.run()
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/aku/aku.py", line 163, in run
    return fn(**{AKU: literal})
  File "/home/zyf/nersted/ner/nn/tagger.py", line 79, in train_tagger
    (train, dev, test), ctx_dim = data(device=device)
  File "/home/zyf/nersted/ner/data/dataset.py", line 213, in ace2005
    return fn(*args, **kwargs)
  File "/home/zyf/nersted/ner/data/dataset.py", line 150, in new
    vocab=... + cls.load_word_vectors(),
  File "/home/zyf/nersted/ner/data/dataset.py", line 209, in load_word_vectors
    return LoadGlove(str.lower, name='6B', dim=100)
  File "/home/zyf/nersted/ner/data/proc.py", line 62, in __init__
    *fallbacks, vectors=Glove(name=name, dim=dim, root=project_data_dir),
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 179, in __init__
    super(Glove, self).__init__(root=root, name=name, dim=dim)
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 127, in __init__
    self.cache_(path=path)
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 153, in cache_
    self.load(torch_path)
  File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 111, in load
    self.stoi, self.itos, self.vectors = torch.load(path)
ValueError: too many values to unpack (expected 3)

**Comment by Fi-github** [comment]
> Hi, thanks for your interest.
> 
> Please reinstall the `torchglyph` library by `python3 -m pip install torchglyph==0.2.0` and try again, if it still doesn't work, please post the complete error information here.

I want to try to find out if the input is causing more parameters and try to see if the useless parameters can be ignored

**Comment by Fi-github** [comment]
> > 
> 
> Thank you for your reply！ Problem solved. But there is a new issues have emerged： Traceback (most recent call last): File "/home/zyf/anaconda3/envs/nested/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/zyf/anaconda3/envs/nested/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/zyf/nersted/ner/**main**.py", line 9, in app.run() File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/aku/aku.py", line 163, in run return fn(**{AKU: literal}) File "/home/zyf/nersted/ner/nn/tagger.py", line 79, in train_tagger (train, dev, test), ctx_dim = data(device=device) File "/home/zyf/nersted/ner/data/dataset.py", line 213, in ace2005 return fn(*args, **kwargs) File "/home/zyf/nersted/ner/data/dataset.py", line 150, in new vocab=... + cls.load_word_vectors(), File "/home/zyf/nersted/ner/data/dataset.py", line 209, in load_word_vectors return LoadGlove(str.lower, name='6B', dim=100) File "/home/zyf/nersted/ner/data/proc.py", line 62, in **init** *fallbacks, vectors=Glove(name=name, dim=dim, root=project_data_dir), File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 179, in **init** super(Glove, self).**init**(root=root, name=name, dim=dim) File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 127, in **init** self.cache_(path=path) File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 153, in cache_ self.load(torch_path) File "/home/zyf/anaconda3/envs/nested/lib/python3.8/site-packages/torchglyph/vocab.py", line 111, in load self.stoi, self.itos, self.vectors = torch.load(path) ValueError: too many values to unpack (expected 3)

I want to try to find out if the input is causing more parameters and try to see if the useless parameters can be ignored

**Comment by speedcell4** [comment]
Sorry, this issue is also related to the breaking changes of the two latest versions of `torchglyph`.
Please move to the `data/glove` directory, remove the `glove.6B.100d.pt` file, and try again.

**Comment by Fi-github** [comment]
> Sorry, this issue is also related to the breaking changes of the two latest versions of `torchglyph`. Please move to the `data/glove` directory, remove the `glove.6B.100d.pt` file, and try again.

The code works now, thank you very much! I am interested in your work and will keep you posted if I have any new ideas or questions.

**Comment by speedcell4** [comment]
Thank you, I am glad to hear that~
I will close this issue, if you have any further ideas or questions, please raise a new one.
